# Generated by Django 3.2 on 2021-07-27 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
            ],
            options={
                'verbose_name': '商品分类信息',
                'verbose_name_plural': '商品分类信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.IntegerField(default=1, verbose_name='性别(1-男 2-女)')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('code', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱地址')),
                ('state', models.IntegerField(default=1, verbose_name='会员状态(1-启用 2-禁用 3-后台管理员)')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkman', models.CharField(max_length=32, verbose_name='联系人')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('code', models.CharField(max_length=6, verbose_name='邮编')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('total', models.FloatField(verbose_name='总金额')),
                ('state', models.SmallIntegerField(verbose_name='订单状态(0-新订单 1-已发货 2-已收货 3-无效订单)')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=32, verbose_name='商品名称')),
                ('company', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('content', models.TextField(verbose_name='详情描述')),
                ('price', models.FloatField(verbose_name='商品单价')),
                ('picname', models.ImageField(upload_to='upload/%Y/%m', verbose_name='商品图片')),
                ('store', models.IntegerField(default=0, verbose_name='库存量')),
                ('num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('clicknum', models.IntegerField(default=0, verbose_name='点击次数')),
                ('state', models.IntegerField(default=1, verbose_name='商品状态(1-新添加 2-在售 3-下架)')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.types', verbose_name='类别ID')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品单价')),
                ('num', models.IntegerField(verbose_name='商品数量')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.goods', verbose_name='商品id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.orders', verbose_name='订单id号')),
            ],
            options={
                'verbose_name': '订单信息详情表',
                'verbose_name_plural': '订单信息详情表',
            },
        ),
    ]
